---
tags: [spring-data, elasticsearch]
projects: [spring-data-elasticsearch]
---
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-accessing-data-elasticsearch
This guide walks you through the process of using https://projects.spring.io/spring-data-elasticsearch/[Spring Data Elasticsearch] to build an application that indexes data and searches it from https://www.elastic.co/products/elasticsearch[Elasticsearch], a distributed, RESTful search and analytics engine.


== What you'll build

You will store `Movie` POJO in a Elasticsearch index using Spring Data Elasticsearch.

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]

[[initial]]
== Install and launch Elasticsearch
With your project set up, you can install and launch the Elasticsearch.


If you are using a Mac with homebrew, this is as simple as:

    $ brew install elasticsearch@2.3
    
Spring Data Elasticsearch is complaint with Elasticsearch 2.3.

For other systems with package management, such as Redhat, Ubuntu, Debian, CentOS, and Windows, see instructions at https://www.elastic.co/guide/en/elasticsearch/reference/2.3/_installation.html.

After you install Elasticsearch, launch it in a console window. This command also starts up a server process. 


    $ cd /usr/local/Cellar/elasticsearch@2.3/2.3.5/libexec/bin
    $ ./elasticsearch --cluster.name test_cluster
    
    
== Define a simple entity
Elasticsearch is a near real time search platform which is comprised of the following:

    - https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#_cluster[Cluster]
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#_node[Node]
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#_index[Index]
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#_type[Type]
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#_document[Document]
    - https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#getting-started-shards-and-replicas[Shards & Replicas]
    
We create an Elasticsearch document using `Movie`

`src/main/java/hello/Movie.java`
[source,java]
----
include::complete/src/main/java/hello/Movie.java[]
----

Here you have a `Movie` class with four attributes, `id`, `name`, `year` and `genre`. The `id` is mostly for uniquely searching a document in Elasticsearch. You also have a single constructor to populate the entities when creating a new instance.

The `Movie` POJO has `@Document` annotation which defines the https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#_index[`index`] and https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#_type[`type`]. For those coming from the background of relational db, can associate index to a database and a type to a table inside a database. However, there is no direct similarity, this analogy is used only for an understanding purpose.

`id` field is annotated with `@id` to identify it as the unique identifier for the given document.

The other three properties, `name`, `year` and `genre`, are left unannotated. It is assumed that they'll be mapped to fields that share the same name as the properties themselves.

The convenient `toString()` method will print out the details about a movie.



== Create simple search queries
Spring Data Elasticsearch focuses on storing and searching data using Elasticsearch. It also inherits functionality from the Spring Data Commons project, such as the ability to derive queries. Essentially, you don't have to learn the query language of Elasticsearch; you can simply write a handful of methods and the queries are written for you.


To see how this works, create a repository interface that queries `Movie` documents.

`src/main/java/hello/MovieRepository.java`
[source,java]
----
include::complete/src/main/java/hello/MovieRepository.java[]
----
    
`MovieRepository` extends the `ElasticsearchRepository` interface and plugs in the type of values and id it works with: `Movie` and `String`. Out-of-the-box, this interface comes with many operations, including standard search operations. You can check some of the methods http://docs.spring.io/spring-data/elasticsearch/docs/3.0.0.M1/reference/html/#elasticsearch.query-methods.criterions[here].

You can define other queries as needed by simply declaring their method signature. In this case, you add `findByName`, which essentially seeks documents of type `Movie` and finds the one that matches on `name`.

In a typical Java application, you write a class that implements `MovieRepository` and craft the queries yourself. What makes Spring Data Elasticsearch so useful is the fact that you don't have to create this implementation. Spring Data Elasticsearch creates it on the fly when you run the application.

Let's wire this up and see what it looks like!

== Setting Application configurations
Here you set the configurations required for the application.

`src/main/resources/application.properties`
[source,text]
----
include::complete/src/main/resources/application.properties[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-application.adoc[]

Normally you would use port 9200 when you query your elastic server. But when we programmatically reach it we are using 9300. Hence, the `cluster-nodes` property is set to `localhost:9300`. Also, the `cluster-name` property is set to `test_cluster`. This clustername was passed as an argument at the time of starting the elasticsearch in the local machine.

== Create an Application class
Here you create an Application class with all the components.

`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/spring-boot-application.adoc[]

Spring Boot will handle those repositories automatically as long as they are included
in the same package (or a sub-package) of your `@SpringBootApplication` class. For more control over the
registration process, you can use the `@EnableElasticsearchRepositories` annotation.

NOTE: By default, `@EnableElasticsearchRepositories` will scan the current package for any interfaces that extend one of Spring Data's repository interfaces. Use it's `basePackageClasses=MyRepository.class` to safely tell Spring Data Elasticsearch to scan a different root package by type if your project layout has multiple projects and its not finding your repositories.

Spring Data Elasticsearch uses the `ElasticsearchTemplate` to execute the queries behind your `find*` methods. You can
use the template yourself for more complex queries, but this guide doesn't cover that.

`Application` includes a `main()` method that autowires an instance of `MovieRepository`: Spring Data
Elasticsearch dynamically creates a proxy and injects it there. We use the `MovieRepository` through a few
tests. First, it saves a handful of `Movie` objects, demonstrating the `save()` method and setting
up some data to work with. Next, it calls `findByName()` to fetch `Movie` objects from the index.
Then it calls `findByGenre()` to fetch all `Movie` objects by their genre. Finally, it calls
`findByYear()` to find all movies in the year 2013.

Spring Boot will handle those repositories automatically as long as they are included
in the same package (or a sub-package) of your `@SpringBootApplication` class. For more control over the
registration process, you can use the `@EnableElasticsearchRepositories` annotation.

Spring Data Elasticsearch uses the `ElasticsearchTemplate` to execute the queries behind your `find*` methods. You can
use the template yourself for more complex queries, but this guide doesn't cover that.

`Application` includes a `main()` method that autowires an instance of `MovieRepository`: Spring Data
Elasticsearch dynamically creates a proxy and injects it there. We use the `MovieRepository` through a few
tests. First, it saves a handful of `Movie` objects, demonstrating the `save()` method and setting
up some data to work with. Next, it calls `findByName()` to fetch `Movie` objects from the index.
Then it calls `findByGenre()` to fetch all `Movie` objects by their genre. Finally, it calls
`findByYear()` to find all movies in the year 2013.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_mainhead.adoc[]
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]
    
    
As our `Application` implements `CommandLineRunner`, the `run` method is invoked automatically when boot
starts. You should see something like this (with other stuff like queries as well):
....
== Movies found with findByName('Rush'):
[Movie [id=tt1979320, name=Rush, year=2013, genre=[Action, Biography, Drama]]]

== Movies found with findByGenre('Drama'):
Movie [id=tt0111161, name=The Shawshank Redemption, year=1994, genre=[Crime, Drama]]
Movie [id=tt1979320, name=Rush, year=2013, genre=[Action, Biography, Drama]]

== Movies found with findByGenreIn(['Drama']):
Movie [id=tt0111161, name=The Shawshank Redemption, year=1994, genre=[Crime, Drama]]
Movie [id=tt1979320, name=Rush, year=2013, genre=[Action, Biography, Drama]]

== Movies found with findByYear(2013):
[Movie [id=tt1979320, name=Rush, year=2013, genre=[Action, Biography, Drama]]]

== Movies found with findByYearBefore(2000):
Movie [id=tt0111161, name=The Shawshank Redemption, year=1994, genre=[Crime, Drama]]
....

== Summary
Congratulations! You set up a Elasticsearch server and wrote a simple application that uses Spring Data Elasticsearch to save documents to and search them from the index -- all without writing a concrete repository implementation.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]
